name: Run yarn test

on:
  push:
    branches:
      - main # replace this with the default branch name if different
  pull_request:
    branches:
      - main # replace this with the default branch name if different

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # or another version you prefer

    - name: Install dependencies
      run: yarn install

    - name: Run yarn test
      run: yarn test
